// <auto-generated />
using System;
using HDP.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HDP.Infra.Migrations
{
    [DbContext(typeof(HDPContext))]
    [Migration("20250716233115_departamentoMigration")]
    partial class departamentoMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HDP.Core.Entidade.Categoria", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .IsRequired()
                        .HasColumnType("DATE")
                        .HasColumnName("Data_Hora_Alt")
                        .HasComment("Data Hora Alteração do Registro");

                    b.Property<DateTime?>("DataHoraInclusao")
                        .IsRequired()
                        .HasColumnType("DATE")
                        .HasColumnName("Data_Hora_Inc")
                        .HasComment("Data Hora Inclusão do Registro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nome")
                        .HasComment("Nome da Categoria");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status")
                        .HasComment("0 Ativo, 1 Inativo");

                    b.Property<string>("UsuarioAlteracao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Usuario_Alt")
                        .HasComment("Usuário de Alteração");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Usuario_Inc")
                        .HasComment("Usuário de Inclusão");

                    b.HasKey("Id");

                    b.ToTable("Categoria", "dbo");
                });

            modelBuilder.Entity("HDP.Core.Entidade.Departamento", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .IsRequired()
                        .HasColumnType("DATE")
                        .HasColumnName("Data_Hora_Alt")
                        .HasComment("Data Hora Alteração do Registro");

                    b.Property<DateTime?>("DataHoraInclusao")
                        .IsRequired()
                        .HasColumnType("DATE")
                        .HasColumnName("Data_Hora_Inc")
                        .HasComment("Data Hora Inclusão do Registro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nome")
                        .HasComment("Nome da Categoria");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status")
                        .HasComment("0 Ativo, 1 Inativo");

                    b.Property<string>("UsuarioAlteracao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Usuario_Alt")
                        .HasComment("Usuário de Alteração");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Usuario_Inc")
                        .HasComment("Usuário de Inclusão");

                    b.HasKey("Id");

                    b.ToTable("Departamento", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
